#!/bin/sh -e
# This is run instead of /sbin/init to just run the program and shut down asap

echo "Entering tmc-init"

EXERCISE_TAR=/dev/ubdb
OUTPUT_FILE=/dev/ubdc
WORKDIR=/tmc

# Ensure UML block device nodes exist
[ -e /dev/ubda ] || mknod /dev/ubda b 98 0
[ -e /dev/ubdb ] || mknod /dev/ubdb b 98 16
[ -e /dev/ubdc ] || mknod /dev/ubdc b 98 32

# Mount /proc and /sys
mount -t proc proc /proc
mount -t sysfs sys /sys

# Go to working dir
mkdir -p $WORKDIR
cd $WORKDIR

# Unzip exercise
tar xf $EXERCISE_TAR

#TODO: tmc-run without root privileges!

# Compile and run the program
echo "Starting tmc-run"
./tmc-run
echo "Completed tmc-run"

# Write the result
cat output.txt > $OUTPUT_FILE

echo "Shutting down..."

# Shut down
sync
exec halt -f
