source 'http://rubygems.org'

gem 'rake'
gem 'rack'
gem 'multi_json'
gem 'activesupport'
gem 'hash-deep-merge' # TODO: this is buggy - it doesn't always clone stuff properly. Use active_support/core_ext/hash/deep_merge instead.
gem 'sqlite3'
gem 'daemons'

gem 'test-unit'
gem 'rack-test'

gem 'pry'
